### ISSUE TITLE
Request for version tags/releases

### ISSUE THREAD

**Issue by tgurr** [GetDKAN/data-catalog-frontend#46]
It would be very helpful to at least have releases tagged for data-catalog-frontend so one could see if an update is available and/or recommended without having to dig through git commits.

**Comment by dgading** [comment]
Sorry for the delay here. We have been working on standing up and switching internally to use https://github.com/GetDKAN/data-catalog-react. I am cleaning up this repo and am going to try and cut tagged versions since I won't be working on it as much. Gatsby has caused more issues than it solved over the past year with the extra node creation step. 

Since we are starting fresh on data-catalog-react, I'm going to try and do better with the versioning there as well.
